#!/usr/bin/env node
/**
 * animal-data.plain.json を読み、難読化した animal-data.js を出力する。
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const PLAIN = path.join(ROOT, 'animal-data.plain.json');
const OUT = path.join(ROOT, 'animal-data.js');

function main() {
  const json = fs.readFileSync(PLAIN, 'utf8');
  const b64 = Buffer.from(json, 'utf8').toString('base64');
  const js = `// Generated by scripts/obfuscate-animal.js — edit animal-data.plain.json and re-run to update
(function(){try{var b=atob("${b64}");var u=new Uint8Array(b.length);for(var i=0;i<b.length;i++)u[i]=b.charCodeAt(i);var d=JSON.parse(new TextDecoder("utf-8").decode(u));window.__ANIMAL_DATA__=d;}catch(e){console.error("Animal data load error",e);window.__ANIMAL_DATA__={animalTiers:[]};}})();
`;
  fs.writeFileSync(OUT, js, 'utf8');
  console.log('Written:', OUT);
  console.log('  payload length (base64):', b64.length);
}

main();
